In [2]:
# Check Python version
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [3]:
def unit_converter():
    """
    Converts between different units of measurement (length, weight, volume).

    Parameters:
    None (takes user input)

    Returns:
    float: The converted value
    """
    print("\n" + "="*50)
    print("UNIT CONVERTER")
    print("="*50)

    try:
        # Choose conversion type
        print("\nChoose conversion type:")
        print("1. Length (meters <-> feet)")
        print("2. Weight (kilograms <-> pounds)")
        print("3. Volume (liters <-> gallons)")

        choice = input("\nEnter your choice (1/2/3): ").strip()

        if choice not in ['1', '2', '3']:
            print("Error: Invalid choice. Please select 1, 2, or 3.")
            return None

        # Get value to convert
        value = float(input("Enter the value to convert: "))

        # Perform conversion based on choice
        if choice == '1':  # Length
            print("\nLength Conversion:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = input("Enter your choice (1/2): ").strip()

            if sub_choice == '1':
                result = value * 3.28084  # meters to feet
                print(f"\n{value} meters = {result:.4f} feet")
                return result
            elif sub_choice == '2':
                result = value / 3.28084  # feet to meters
                print(f"\n{value} feet = {result:.4f} meters")
                return result
            else:
                print("Error: Invalid sub-choice.")
                return None

        elif choice == '2':  # Weight
            print("\nWeight Conversion:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = input("Enter your choice (1/2): ").strip()

            if sub_choice == '1':
                result = value * 2.20462  # kg to lbs
                print(f"\n{value} kilograms = {result:.4f} pounds")
                return result
            elif sub_choice == '2':
                result = value / 2.20462  # lbs to kg
                print(f"\n{value} pounds = {result:.4f} kilograms")
                return result
            else:
                print("Error: Invalid sub-choice.")
                return None

        else:  # Volume
            print("\nVolume Conversion:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = input("Enter your choice (1/2): ").strip()

            if sub_choice == '1':
                result = value * 0.264172  # liters to gallons
                print(f"\n{value} liters = {result:.4f} gallons")
                return result
            elif sub_choice == '2':
                result = value / 0.264172  # gallons to liters
                print(f"\n{value} gallons = {result:.4f} liters")
                return result
            else:
                print("Error: Invalid sub-choice.")
                return None

    except ValueError:
        print("Error: Please enter a valid numeric value.")
        return None
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return None

# Test the function
unit_converter()


UNIT CONVERTER

Choose conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)

Enter your choice (1/2/3): 1
Enter the value to convert: 12

Length Conversion:
1. Meters to Feet
2. Feet to Meters
Enter your choice (1/2): 1

12.0 meters = 39.3701 feet


39.37008

In [4]:
def calculate_sum(numbers):
    """
    Calculates the sum of numbers in a list.

    Parameters:
    numbers (list): List of numbers

    Returns:
    float: Sum of all numbers
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of numbers in a list.

    Parameters:
    numbers (list): List of numbers

    Returns:
    float: Average of all numbers
    """
    if not numbers:
        return 0
    return sum(numbers) / len(numbers)

def calculate_maximum(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
    numbers (list): List of numbers

    Returns:
    float: Maximum number
    """
    if not numbers:
        return None
    return max(numbers)

def calculate_minimum(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
    numbers (list): List of numbers

    Returns:
    float: Minimum number
    """
    if not numbers:
        return None
    return min(numbers)

def math_operations_menu():
    """
    Main function to perform mathematical operations on a list of numbers.

    Parameters:
    None (takes user input)

    Returns:
    None (displays results)
    """
    print("\n" + "="*50)
    print("MATHEMATICAL OPERATIONS ON LIST")
    print("="*50)

    try:
        # Get operation choice
        print("\nChoose operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("\nEnter your choice (1-4): ").strip()

        if choice not in ['1', '2', '3', '4']:
            print("Error: Invalid choice. Please select 1-4.")
            return

        # Get list of numbers
        numbers_input = input("Enter numbers separated by spaces: ").strip()

        if not numbers_input:
            print("Error: Empty input. Please enter at least one number.")
            return

        # Convert input to list of floats
        numbers = []
        for num in numbers_input.split():
            try:
                numbers.append(float(num))
            except ValueError:
                print(f"Error: '{num}' is not a valid number.")
                return

        if not numbers:
            print("Error: No valid numbers provided.")
            return

        # Perform selected operation
        print(f"\nNumbers: {numbers}")

        if choice == '1':
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == '2':
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == '3':
            result = calculate_maximum(numbers)
            print(f"Maximum: {result}")
        else:  # choice == '4'
            result = calculate_minimum(numbers)
            print(f"Minimum: {result}")

    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Test the function
math_operations_menu()


MATHEMATICAL OPERATIONS ON LIST

Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum

Enter your choice (1-4): 2
Enter numbers separated by spaces: 11 23 44 55

Numbers: [11.0, 23.0, 44.0, 55.0]
Average: 33.25


In [5]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
    lst (list): Input list

    Returns:
    list: New list containing every other element
    """
    return lst[::2]

# Test
print("1. Extract every other element:")
print(extract_every_other([1, 2, 3, 4, 5, 6]))  # [1, 3, 5]
print("-" * 40)


# 2. Slice a Sublist
def get_sublist(lst, start, end):
    """
    Returns a sublist from start to end (inclusive).

    Parameters:
    lst (list): Input list
    start (int): Starting index
    end (int): Ending index

    Returns:
    list: Sublist from start to end
    """
    return lst[start:end+1]

# Test
print("2. Slice a sublist:")
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # [3, 4, 5]
print("-" * 40)


# 3. Reverse a List Using Slicing
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): Input list

    Returns:
    list: Reversed list
    """
    return lst[::-1]

# Test
print("3. Reverse a list:")
print(reverse_list([1, 2, 3, 4, 5]))  # [5, 4, 3, 2, 1]
print("-" * 40)


# 4. Remove First and Last Elements
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.

    Parameters:
    lst (list): Input list

    Returns:
    list: Sublist without first and last elements
    """
    if len(lst) <= 2:
        return []
    return lst[1:-1]

# Test
print("4. Remove first and last elements:")
print(remove_first_last([1, 2, 3, 4, 5]))  # [2, 3, 4]
print(remove_first_last([1, 2]))  # []
print("-" * 40)


# 5. Get First n Elements
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements to extract

    Returns:
    list: First n elements
    """
    return lst[:n]

# Test
print("5. Get first n elements:")
print(get_first_n([1, 2, 3, 4, 5], 3))  # [1, 2, 3]
print("-" * 40)


# 6. Extract Last n Elements
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements to extract

    Returns:
    list: Last n elements
    """
    if n <= 0:
        return []
    return lst[-n:]

# Test
print("6. Get last n elements:")
print(get_last_n([1, 2, 3, 4, 5], 2))  # [4, 5]
print("-" * 40)


# 7. Extract Elements in Reverse Order (Skip One)
def reverse_skip(lst):
    """
    Extracts every second element starting from second-to-last, moving backward.

    Parameters:
    lst (list): Input list

    Returns:
    list: Elements in reverse order with skip
    """
    # Start from second-to-last (index -2), go backward, step -2
    return lst[-2::-2]

# Test
print("7. Reverse skip:")
print(reverse_skip([1, 2, 3, 4, 5, 6]))  # [5, 3, 1]
print(reverse_skip([1, 2, 3, 4, 5]))    # [4, 2]
print("-" * 40)

1. Extract every other element:
[1, 3, 5]
----------------------------------------
2. Slice a sublist:
[3, 4, 5]
----------------------------------------
3. Reverse a list:
[5, 4, 3, 2, 1]
----------------------------------------
4. Remove first and last elements:
[2, 3, 4]
[]
----------------------------------------
5. Get first n elements:
[1, 2, 3]
----------------------------------------
6. Get last n elements:
[4, 5]
----------------------------------------
7. Reverse skip:
[5, 3, 1]
[4, 2]
----------------------------------------


In [6]:
# 1. Flatten a Nested List
def flatten(lst):
    """
    Flattens a nested list into a single list (1 level depth).

    Parameters:
    lst (list): Nested list

    Returns:
    list: Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(item)
        else:
            result.append(item)
    return result

# Test
print("1. Flatten nested list:")
print(flatten([[1, 2], [3, 4], [5]]))  # [1, 2, 3, 4, 5]
print("-" * 40)


# 2. Access Nested List Element
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
    lst (list): Nested list
    indices (list): List of indices

    Returns:
    element at the specified position
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

# Test
print("2. Access nested element:")
nested_lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(nested_lst, [1, 2]))  # 6
print("-" * 40)


# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list (any depth).

    Parameters:
    lst (list): Nested list

    Returns:
    int/float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Test
print("3. Sum of nested list:")
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # 21
print("-" * 40)


# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): Nested list
    elem: Element to remove

    Returns:
    list: Modified list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            # Recursively process nested lists
            cleaned = remove_element(item, elem)
            if cleaned:  # Only add non-empty lists
                result.append(cleaned)
        elif item != elem:
            result.append(item)
    return result

# Test
print("4. Remove element from nested list:")
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # [[1], [3], [4, 5]]
print("-" * 40)


# 5. Find Maximum Element in a Nested List
def find_max(lst):
    """
    Finds the maximum element in a nested list (any depth).

    Parameters:
    lst (list): Nested list

    Returns:
    Maximum element
    """
    max_val = float('-inf')

    for item in lst:
        if isinstance(item, list):
            val = find_max(item)
            if val > max_val:
                max_val = val
        else:
            if item > max_val:
                max_val = item

    return max_val if max_val != float('-inf') else None

# Test
print("5. Find maximum in nested list:")
print(find_max([[1, 2], [3, [4, 5]], 6]))  # 6
print("-" * 40)


# 6. Count Occurrences in a Nested List
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): Nested list
    elem: Element to count

    Returns:
    int: Number of occurrences
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count

# Test
print("6. Count occurrences:")
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # 3
print("-" * 40)


# 7. Deep Flatten (any depth)
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list (any depth).

    Parameters:
    lst (list): Deeply nested list

    Returns:
    list: Completely flattened list
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result

# Test
print("7. Deep flatten:")
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # [1, 2, 3, 4, 5, 6, 7, 8]
print("-" * 40)


# 8. Nested List Average
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): Nested list

    Returns:
    float: Average of all elements
    """
    flattened = deep_flatten(lst)
    if not flattened:
        return 0
    return sum(flattened) / len(flattened)

# Test
print("8. Nested list average:")
print(average_nested([[1, 2], [3, 4], [5, 6]]))  # 3.5
print("-" * 40)

1. Flatten nested list:
[1, 2, 3, 4, 5]
----------------------------------------
2. Access nested element:
6
----------------------------------------
3. Sum of nested list:
21
----------------------------------------
4. Remove element from nested list:
[[1], [3], [4, 5]]
----------------------------------------
5. Find maximum in nested list:
6
----------------------------------------
6. Count occurrences:
3
----------------------------------------
7. Deep flatten:
[1, 2, 3, 4, 5, 6, 7, 8]
----------------------------------------
8. Nested list average:
3.5
----------------------------------------


In [7]:
import numpy as np
import time

In [8]:
print("="*60)
print("PROBLEM 1: Array Creation")
print("="*60)

# 1. Initialize an empty array with size 2x2
empty_arr = np.empty((2, 2))
print("1. Empty array (2x2):")
print(empty_arr)
print()

# 2. Initialize an all one array with size 4x2
ones_arr = np.ones((4, 2))
print("2. Ones array (4x2):")
print(ones_arr)
print()

# 3. Return a new array filled with fill_value
fill_arr = np.full((3, 3), 7)
print("3. Array filled with 7 (3x3):")
print(fill_arr)
print()

# 4. Return a new array of zeros with same shape as given array
template = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(template)
print("4. Zeros like template array:")
print(zeros_like_arr)
print()

# 5. Return a new array of ones with same shape as given array
ones_like_arr = np.ones_like(template)
print("5. Ones like template array:")
print(ones_like_arr)
print()

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("6. List to NumPy array:")
print(f"Original list: {new_list}")
print(f"NumPy array: {numpy_array}")
print(f"Type: {type(numpy_array)}")

PROBLEM 1: Array Creation
1. Empty array (2x2):
[[3.25862115e-315 0.00000000e+000]
 [8.54389148e-254 2.04757725e-306]]

2. Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like template array:
[[0 0 0]
 [0 0 0]]

5. Ones like template array:
[[1 1 1]
 [1 1 1]]

6. List to NumPy array:
Original list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Type: <class 'numpy.ndarray'>


In [9]:
print("="*60)
print("PROBLEM 1: Array Creation")
print("="*60)

# 1. Initialize an empty array with size 2x2
empty_arr = np.empty((2, 2))
print("1. Empty array (2x2):")
print(empty_arr)
print()

# 2. Initialize an all one array with size 4x2
ones_arr = np.ones((4, 2))
print("2. Ones array (4x2):")
print(ones_arr)
print()

# 3. Return a new array filled with fill_value
fill_arr = np.full((3, 3), 7)
print("3. Array filled with 7 (3x3):")
print(fill_arr)
print()

# 4. Return a new array of zeros with same shape as given array
template = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(template)
print("4. Zeros like template array:")
print(zeros_like_arr)
print()

# 5. Return a new array of ones with same shape as given array
ones_like_arr = np.ones_like(template)
print("5. Ones like template array:")
print(ones_like_arr)
print()

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("6. List to NumPy array:")
print(f"Original list: {new_list}")
print(f"NumPy array: {numpy_array}")
print(f"Type: {type(numpy_array)}")

PROBLEM 1: Array Creation
1. Empty array (2x2):
[[3.22574228e-315 0.00000000e+000]
 [6.74136204e-310 5.78741383e-317]]

2. Ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like template array:
[[0 0 0]
 [0 0 0]]

5. Ones like template array:
[[1 1 1]
 [1 1 1]]

6. List to NumPy array:
Original list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Type: <class 'numpy.ndarray'>


In [10]:
print("\n" + "="*60)
print("PROBLEM 2: Array Manipulation")
print("="*60)

# 1. Create an array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr_range)
print(f"Shape: {arr_range.shape}")
print()

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 matrix with values 0 to 8:")
print(matrix_3x3)
print()

# 3. Create a 3x3 identity matrix
identity_3x3 = np.eye(3)
print("3. 3x3 identity matrix:")
print(identity_3x3)
print()

# 4. Create a random array of size 30 and find the mean
random_arr = np.random.random(30)
mean_val = random_arr.mean()
print("4. Random array (size 30) - first 10 elements:")
print(random_arr[:10])
print(f"Mean of array: {mean_val:.6f}")
print()

# 5. Create a 10x10 array with random values, find min and max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("5. 10x10 random array - shape:", random_10x10.shape)
print(f"Minimum value: {min_val:.6f}")
print(f"Maximum value: {max_val:.6f}")
print()

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1  # 5th element (index 4)
print("6. Zero array with 5th element replaced by 1:")
print(zero_arr)
print()

# 7. Reverse an array
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr_to_reverse[::-1]
print("7. Reverse array:")
print(f"Original: {arr_to_reverse}")
print(f"Reversed: {reversed_arr}")
print()

# 8. Create a 2d array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("8. 5x5 array with 1 on border, 0 inside:")
print(border_arr)
print()

# 9. Create an 8x8 matrix with checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Set odd rows, even columns to 1
checkerboard[::2, 1::2] = 1  # Set even rows, odd columns to 1
print("9. 8x8 checkerboard pattern:")
print(checkerboard)


PROBLEM 2: Array Manipulation
1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,)

2. 3x3 matrix with values 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30) - first 10 elements:
[0.31534677 0.2686056  0.43916903 0.35227567 0.67962654 0.08906489
 0.01248059 0.47549249 0.73779716 0.75187145]
Mean of array: 0.446919

5. 10x10 random array - shape: (10, 10)
Minimum value: 0.014867
Maximum value: 0.997857

6. Zero array with 5th element replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reverse array:
Original: [1 2 0 0 4 0]
Reversed: [0 4 0 0 2 1]

8. 5x5 array with 1 on border, 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 

In [11]:
print("\n" + "="*60)
print("PROBLEM 3: Basic Array Operations")
print("="*60)

# Define arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Given arrays:")
print(f"x =\n{x}")
print(f"y =\n{y}")
print(f"v = {v}")
print(f"w = {w}")
print()

# 1. Add the two arrays
print("1. Addition:")
print(f"x + y =\n{x + y}")
print(f"v + w = {v + w}")
print()

# 2. Subtract the two arrays
print("2. Subtraction:")
print(f"x - y =\n{x - y}")
print(f"v - w = {v - w}")
print()

# 3. Multiply with integers
print("3. Multiplication with integers:")
print(f"x * 3 =\n{x * 3}")
print(f"v * 5 = {v * 5}")
print()

# 4. Square of each element
print("4. Square of each element:")
print(f"x^2 =\n{np.square(x)}")
print(f"v^2 = {np.square(v)}")
print()

# 5. Dot products
print("5. Dot products:")
print(f"v · w = {np.dot(v, w)}")
print(f"x · v = {np.dot(x, v)}")
print(f"x · y =\n{np.dot(x, y)}")
print()

# 6. Concatenate x and y along row, v and w along column
concat_row = np.concatenate((x, y), axis=0)  # along rows (vertical)
concat_col_vw = np.column_stack((v, w))  # v and w as columns
print("6. Concatenation:")
print(f"x and y concatenated along rows:\n{concat_row}")
print(f"v and w concatenated along columns:\n{concat_col_vw}")
print()

# 7. Concatenate x and v
print("7. Concatenate x and v:")
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except ValueError as e:
    print(f"Error: {e}")
    print("Explanation: Cannot concatenate x (2x2) and v (2,) because they have different dimensions.")
    print("x has shape (2,2) while v has shape (2,). To concatenate, reshape v to (2,1) or (1,2).")

    # Solution
    v_reshaped = v.reshape(2, 1)
    concat_xv_solution = np.concatenate((x, v_reshaped), axis=1)
    print(f"\nSolution: Reshape v to {v_reshaped.shape} and concatenate along columns:\n{concat_xv_solution}")


PROBLEM 3: Basic Array Operations
Given arrays:
x =
[[1 2]
 [3 5]]
y =
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. Addition:
x + y =
[[ 6  8]
 [10 13]]
v + w = [20 22]

2. Subtraction:
x - y =
[[-4 -4]
 [-4 -3]]
v - w = [-2 -2]

3. Multiplication with integers:
x * 3 =
[[ 3  6]
 [ 9 15]]
v * 5 = [45 50]

4. Square of each element:
x^2 =
[[ 1  4]
 [ 9 25]]
v^2 = [ 81 100]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y =
[[19 22]
 [50 58]]

6. Concatenation:
x and y concatenated along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w concatenated along columns:
[[ 9 11]
 [10 12]]

7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate x (2x2) and v (2,) because they have different dimensions.
x has shape (2,2) while v has shape (2,). To concatenate, reshape v to (2,1) or (1,2).

Solution: Reshape v to (2, 1) and concatenate along columns:

In [12]:
print("\n" + "="*60)
print("PROBLEM 4: Matrix Operations")
print("="*60)

# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print(f"A =\n{A}")
print(f"B =\n{B}")
print()

# 1. Prove A * A^(-1) = I
print("1. Prove A * A^(-1) = I")
A_inv = np.linalg.inv(A)
I_calc = np.dot(A, A_inv)
I_actual = np.eye(2)

print(f"A^(-1) =\n{A_inv}")
print(f"A * A^(-1) =\n{I_calc}")
print(f"Identity matrix I =\n{I_actual}")

# Check if approximately equal (rounding errors)
is_identity = np.allclose(I_calc, I_actual)
print(f"Therefore, A * A^(-1) = I is {is_identity}")
print()

# 2. Prove AB ≠ BA
print("2. Prove AB ≠ BA")
AB = np.dot(A, B)
BA = np.dot(B, A)

print(f"AB =\n{AB}")
print(f"BA =\n{BA}")
print(f"AB == BA? {np.array_equal(AB, BA)}")
print()

# 3. Prove (AB)^T = B^T A^T
print("3. Prove (AB)^T = B^T A^T")
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)

print(f"(AB)^T =\n{AB_T}")
print(f"B^T * A^T =\n{BT_AT}")
print(f"(AB)^T == B^T A^T? {np.allclose(AB_T, BT_AT)}")
print()




PROBLEM 4: Matrix Operations
A =
[[3 4]
 [7 8]]
B =
[[5 3]
 [2 1]]

1. Prove A * A^(-1) = I
A^(-1) =
[[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^(-1) =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix I =
[[1. 0.]
 [0. 1.]]
Therefore, A * A^(-1) = I is True

2. Prove AB ≠ BA
AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
AB == BA? False

3. Prove (AB)^T = B^T A^T
(AB)^T =
[[23 51]
 [13 29]]
B^T * A^T =
[[23 51]
 [13 29]]
(AB)^T == B^T A^T? True



In [13]:
import numpy as np

print("=" * 50)
print("SOLVING SYSTEM OF LINEAR EQUATIONS")
print("=" * 50)
A = np.array([[ 2, -3,  1],
              [ 1, -1,  2],
              [ 3,  1, -1]])

B = np.array([-1, -3, 9])

print("\n" + "=" * 50)
print("STEP 1: Matrices")
print("=" * 50)
print(f"\nMatrix A:\n{A}")
print(f"\nMatrix B:\n{B}")

print("\n" + "=" * 50)
print("STEP 2: Determinant Check")
print("=" * 50)
det = np.linalg.det(A)
print(f"\nDeterminant: {det:.4f}")
if det == 0:
    print("No unique solution exists!")
else:
    print("Unique solution exists")

print("\n" + "=" * 50)
print("STEP 3: Inverse of A")
print("=" * 50)
A_inv = np.linalg.inv(A)
print(f"\nA inverse:\n{A_inv}")
print(f"\nA x A_inv = Identity:")
print(np.round(np.dot(A, A_inv)))

print("\n" + "=" * 50)
print("STEP 4: Solve X = A_inv x B")
print("=" * 50)
X = np.dot(A_inv, B)
print(f"\nx = {X[0]:.4f}")
print(f"y = {X[1]:.4f}")
print(f"z = {X[2]:.4f}")

print("\n" + "=" * 50)
print("STEP 5: Verify AX = B")
print("=" * 50)
print(f"\nAX    = {np.dot(A, X)}")
print(f"B     = {B}")
print(f"AX = B: {np.allclose(np.dot(A, X), B)}")

print("\n" + "=" * 50)
print("STEP 6: Manual Verification")
print("=" * 50)
x, y, z = X[0], X[1], X[2]
print(f"\nEq1: 2({x:.0f}) - 3({y:.0f}) + ({z:.0f})  = {2*x - 3*y + z:.0f}  (expected -1)")
print(f"Eq2:  ({x:.0f}) -  ({y:.0f}) + 2({z:.0f}) = {x - y + 2*z:.0f}  (expected -3)")
print(f"Eq3: 3({x:.0f}) +  ({y:.0f}) - ({z:.0f})  = {3*x + y - z:.0f}   (expected  9)")

print("\n" + "=" * 50)
print("STEP 7: Using linalg.solve")
print("=" * 50)
X_solve = np.linalg.solve(A, B)
print(f"\nx = {X_solve[0]:.4f}")
print(f"y = {X_solve[1]:.4f}")
print(f"z = {X_solve[2]:.4f}")
print(f"\nBoth methods match: {np.allclose(X, X_solve)}")

print("\n" + "=" * 50)
print("FINAL ANSWER")
print("=" * 50)
print(f"\nx = {X[0]:.2f}")
print(f"y = {X[1]:.2f}")
print(f"z = {X[2]:.2f}")
print("\n" + "=" * 50)

SOLVING SYSTEM OF LINEAR EQUATIONS

STEP 1: Matrices

Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Matrix B:
[-1 -3  9]

STEP 2: Determinant Check

Determinant: -19.0000
Unique solution exists

STEP 3: Inverse of A

A inverse:
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

A x A_inv = Identity:
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

STEP 4: Solve X = A_inv x B

x = 2.0000
y = 1.0000
z = -2.0000

STEP 5: Verify AX = B

AX    = [-1. -3.  9.]
B     = [-1 -3  9]
AX = B: True

STEP 6: Manual Verification

Eq1: 2(2) - 3(1) + (-2)  = -1  (expected -1)
Eq2:  (2) -  (1) + 2(-2) = -3  (expected -3)
Eq3: 3(2) +  (1) - (-2)  = 9   (expected  9)

STEP 7: Using linalg.solve

x = 2.0000
y = 1.0000
z = -2.0000

Both methods match: True

FINAL ANSWER

x = 2.00
y = 1.00
z = -2.00



In [14]:
print("\n" + "="*70)
print("EXPERIMENT: How Fast is NumPy?")
print("="*70)

# Set parameters
size = 1_000_000  # 1 million elements for vector operations
matrix_size = 1000  # 1000x1000 matrices

print(f"Vector size: {size:,} elements")
print(f"Matrix size: {matrix_size}x{matrix_size}\n")

# Create data
print("Creating data...")
# Python lists
list_a = [i for i in range(size)]
list_b = [i * 2 for i in range(size)]

# NumPy arrays
np_a = np.arange(size)
np_b = np.arange(size) * 2

print("Data created. Running experiments...\n")

# 1. Element-wise Addition
print("-" * 50)
print("1. Element-wise Addition")

# Python lists
start_time = time.time()
list_sum = [list_a[i] + list_b[i] for i in range(size)]
end_time = time.time()
list_add_time = end_time - start_time
print(f"Python Lists: {list_add_time:.6f} seconds")

# NumPy arrays
start_time = time.time()
np_sum = np_a + np_b
end_time = time.time()
np_add_time = end_time - start_time
print(f"NumPy Arrays: {np_add_time:.6f} seconds")
print(f"Speed-up: {list_add_time / np_add_time:.2f}x")

# 2. Element-wise Multiplication
print("\n2. Element-wise Multiplication")

# Python lists
start_time = time.time()
list_product = [list_a[i] * list_b[i] for i in range(size)]
end_time = time.time()
list_mult_time = end_time - start_time
print(f"Python Lists: {list_mult_time:.6f} seconds")

# NumPy arrays
start_time = time.time()
np_product = np_a * np_b
end_time = time.time()
np_mult_time = end_time - start_time
print(f"NumPy Arrays: {np_mult_time:.6f} seconds")
print(f"Speed-up: {list_mult_time / np_mult_time:.2f}x")

# 3. Dot Product
print("\n3. Dot Product")

# Python lists
start_time = time.time()
dot_product = 0
for i in range(size):
    dot_product += list_a[i] * list_b[i]
end_time = time.time()
list_dot_time = end_time - start_time
print(f"Python Lists: {list_dot_time:.6f} seconds")
print(f"Result (first few digits): {dot_product}")

# NumPy arrays
start_time = time.time()
np_dot = np.dot(np_a, np_b)
end_time = time.time()
np_dot_time = end_time - start_time
print(f"NumPy Arrays: {np_dot_time:.6f} seconds")
print(f"Result: {np_dot}")
print(f"Speed-up: {list_dot_time / np_dot_time:.2f}x")

# 4. Matrix Multiplication
print("\n4. Matrix Multiplication (1000x1000)")

# Create matrices
list_matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[i * j for j in range(matrix_size)] for i in range(matrix_size)]
np_matrix1 = np.array(list_matrix1)
np_matrix2 = np.array(list_matrix2)

print(f"Matrix shape: {matrix_size}x{matrix_size}")

# Python lists - basic matrix multiplication
print("\nPython Lists implementation (this will take a while)...")
start_time = time.time()

# Simple triple loop matrix multiplication
list_result = [[0 for _ in range(matrix_size)] for _ in range(matrix_size)]
# Only compute a small portion to avoid extremely long runtime
small_size = 50  # Compute only 50x50 for Python lists
for i in range(small_size):
    for j in range(small_size):
        for k in range(matrix_size):
            list_result[i][j] += list_matrix1[i][k] * list_matrix2[k][j]

end_time = time.time()
list_matmul_time = end_time - start_time
print(f"Python Lists (50x50 only): {list_matmul_time:.6f} seconds")
print(f"Estimated time for full {matrix_size}x{matrix_size}: ~{list_matmul_time * (matrix_size/small_size)**3:.2f} seconds")

# NumPy arrays
print("\nNumPy Arrays implementation...")
start_time = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
np_matmul_time = end_time - start_time
print(f"NumPy Arrays (full {matrix_size}x{matrix_size}): {np_matmul_time:.6f} seconds")

# Summary
print("\n" + "="*50)
print("SUMMARY: Performance Comparison")
print("="*50)

print(f"\n{'Operation':<25} {'Python (s)':<15} {'NumPy (s)':<15} {'Speed-up':<10}")
print("-" * 65)
print(f"{'Element-wise Add':<25} {list_add_time:<15.6f} {np_add_time:<15.6f} {list_add_time/np_add_time:<10.2f}x")
print(f"{'Element-wise Mult':<25} {list_mult_time:<15.6f} {np_mult_time:<15.6f} {list_mult_time/np_mult_time:<10.2f}x")
print(f"{'Dot Product':<25} {list_dot_time:<15.6f} {np_dot_time:<15.6f} {list_dot_time/np_dot_time:<10.2f}x")
print(f"{'Matrix Mult':<25} {'(partial)':<15} {np_matmul_time:<15.6f} {'>1000x':<10}")

print("\n" + "="*50)
print("CONCLUSION")
print("="*50)
print("""
NumPy is significantly faster than pure Python for numerical operations because:
1. Vectorized operations run in C (compiled code) rather than Python loops
2. Memory is contiguous and optimized for CPU cache
3. Utilizes optimized BLAS/LAPACK libraries for linear algebra
4. Broadcasting eliminates the need for explicit loops

For large datasets, NumPy can be 100-1000x faster than pure Python!
""")


EXPERIMENT: How Fast is NumPy?
Vector size: 1,000,000 elements
Matrix size: 1000x1000

Creating data...
Data created. Running experiments...

--------------------------------------------------
1. Element-wise Addition
Python Lists: 0.128266 seconds
NumPy Arrays: 0.005753 seconds
Speed-up: 22.30x

2. Element-wise Multiplication
Python Lists: 0.117288 seconds
NumPy Arrays: 0.006905 seconds
Speed-up: 16.99x

3. Dot Product
Python Lists: 0.234653 seconds
Result (first few digits): 666665666667000000
NumPy Arrays: 0.002486 seconds
Result: 666665666667000000
Speed-up: 94.41x

4. Matrix Multiplication (1000x1000)
Matrix shape: 1000x1000

Python Lists implementation (this will take a while)...
Python Lists (50x50 only): 1.131074 seconds
Estimated time for full 1000x1000: ~9048.59 seconds

NumPy Arrays implementation...
NumPy Arrays (full 1000x1000): 2.063663 seconds

SUMMARY: Performance Comparison

Operation                 Python (s)      NumPy (s)       Speed-up  
-------------------------